drop  table IF EXISTS users CASCADE;
create  TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL unique,
CONSTRAINT pk_user PRIMARY KEY (id)
);

drop table IF EXISTS REQUESTS CASCADE;
create TABLE IF NOT EXISTS REQUESTS (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
requester_id   BIGINT NOT NULL,
description varchar (200) not null,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
constraint fk_requester_id FOREIGN KEY (requester_id) REFERENCES USERS(ID)
);

drop table IF EXISTS items CASCADE;
create table if not exists items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar (50) not null,
description varchar (200) not null,
available  boolean not null,
owner_id BIGINT not null,
request_id BIGINT,
FOREIGN KEY (owner_id) REFERENCES users (id),
FOREIGN KEY (request_id) REFERENCES REQUESTS (id)
);



drop table IF EXISTS BOOKINGS CASCADE;
create TABLE IF NOT EXISTS BOOKINGS (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_time TIMESTAMP WITHOUT TIME ZONE not null,
end_time TIMESTAMP WITHOUT TIME ZONE not null,
item_id BIGINT not null ,
booker BIGINT not null ,
status varchar (16) not null,
FOREIGN KEY (booker) REFERENCES users (id),
FOREIGN KEY (item_id) REFERENCES items (id)
);

drop table IF EXISTS COMMENTS CASCADE;
create TABLE IF NOT EXISTS COMMENTS (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
text varchar (4000) not null,
author BIGINT not null  ,
item_id BIGINT not null ,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
FOREIGN KEY (author) REFERENCES users (id),
FOREIGN KEY (item_id) REFERENCES items (id)
);